# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analizadorlexico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField()),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analizadorlexico.usuario')),
            ],
        ),
    ]
