# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizadorlexico', '0003_auto_20160714_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='usua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
            ],
        ),
    ]
