# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analizadorlexico', '0005_auto_20160722_1848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarios',
            new_name='usuario',
        ),
    ]
