# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analizadorlexico', '0006_auto_20160722_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='densidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=30)),
                ('unicas', models.CharField(max_length=30)),
                ('densidad', models.CharField(max_length=30)),
                ('resultado', models.CharField(max_length=30)),
                ('idparrafo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analizadorlexico.parrafo')),
            ],
        ),
    ]
