# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analizadorlexico', '0007_densidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='hipotesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('densidad', models.CharField(max_length=30)),
                ('sofisticacion', models.CharField(max_length=30)),
                ('variedad', models.CharField(max_length=30)),
                ('idparrafo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analizadorlexico.parrafo')),
            ],
        ),
        migrations.RemoveField(
            model_name='densidade',
            name='idparrafo',
        ),
        migrations.DeleteModel(
            name='densidade',
        ),
    ]
