# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizadorlexico', '0009_auto_20160804_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hipo',
            name='densidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hipo',
            name='sofisticacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hipo',
            name='variedad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
