# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizadorlexico', '0011_auto_20160807_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hipo',
            name='densidad',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='hipo',
            name='sofisticacion',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='hipo',
            name='variedad',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
