# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizadorlexico', '0016_total_avance'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_avance',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
