# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analizadorlexico', '0017_total_avance_total'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuario',
            new_name='usuas',
        ),
    ]
