# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analizadorlexico', '0018_auto_20160817_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='conclusione',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analizadorlexico.usuario'),
        ),
        migrations.AlterField(
            model_name='hipo',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analizadorlexico.usuario'),
        ),
        migrations.AlterField(
            model_name='justi',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analizadorlexico.usuario'),
        ),
        migrations.AlterField(
            model_name='metodologia',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analizadorlexico.usuario'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analizadorlexico.usuario'),
        ),
        migrations.AlterField(
            model_name='parrafo',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analizadorlexico.usuario'),
        ),
        migrations.AlterField(
            model_name='planteamiento',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analizadorlexico.usuario'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analizadorlexico.usuario'),
        ),
        migrations.AlterField(
            model_name='total_avance',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analizadorlexico.usuario'),
        ),
        migrations.DeleteModel(
            name='usuas',
        ),
    ]
