# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analizadorlexico', '0019_auto_20160817_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parrafo',
            name='idusuario',
        ),
        migrations.DeleteModel(
            name='usua',
        ),
        migrations.DeleteModel(
            name='parrafo',
        ),
    ]
