# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizadorlexico', '0020_auto_20160818_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hipo',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
