# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizadorlexico', '0021_auto_20160818_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conclusione',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='justi',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='metodologia',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='planteamiento',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
